services:
  airflow:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: cnpj-data-pipeline
    ports:
      - "8081:8080"
    env_file:
      - .env
    volumes:
      - ./data:/opt/project/data
      - ./airflow:/opt/project/airflow
    restart: unless-stopped
    mem_limit: 10g
    mem_reservation: 6g
