services:
  airflow:
    build: .
    container_name: cnpj-data-pipeline
    ports:
      - "8081:8080"
    env_file:
      - .env
    volumes:
      - ./airflow:/opt/project/airflow
      - ./data:/opt/project/data
      - ./warehouse:/opt/project/warehouse
    command: >
      bash -c "
      airflow standalone
      "
